-- TechPulse - Master Schema (V2 Final Consolidation)
-- This script contains the complete, unified database state including V2 vector logic.
-- Targeted for initialization of fresh project environments.

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. UTILITY FUNCTIONS
-- Automatically update updated_at timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 3. TABLE DEFINITIONS

-- Tenant Profiles: Multi-tenant account settings
CREATE TABLE IF NOT EXISTS tenant_profiles (
    user_id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name         TEXT,
    email             TEXT,
    slack_webhook_url TEXT,
    discord_webhook_url TEXT,
    api_token         TEXT,
    role              TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'auditor', 'premium', 'user')),
    is_admin          BOOLEAN DEFAULT FALSE, -- Deprecated, use 'role'
    status            TEXT DEFAULT 'active',
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- RBAC Helpers
CREATE OR REPLACE FUNCTION get_my_role()
RETURNS TEXT LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT role FROM tenant_profiles WHERE user_id = auth.uid() LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION can_add_rss_source(p_user_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT CASE
    WHEN get_my_role() IN ('admin', 'premium') THEN
      (SELECT COUNT(*) FROM rss_sources WHERE user_id = p_user_id) < 50
    ELSE
      (SELECT COUNT(*) FROM rss_sources WHERE user_id = p_user_id) < 5
  END;
$$;

-- RSS Sources: User-specific feed configurations & health metrics
CREATE TABLE IF NOT EXISTS rss_sources (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name              TEXT NOT NULL,
    url               TEXT NOT NULL,
    is_active         BOOLEAN DEFAULT TRUE,
    last_fetched_at   TIMESTAMPTZ,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT rss_sources_url_userid_key UNIQUE (url, user_id)
);

-- Article Events: Thematic clusters for grouping related news
CREATE TABLE IF NOT EXISTS article_events (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id           UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title             TEXT NOT NULL,
    theme             TEXT,                      -- e.g. "Generative AI", "Regulation"
    centroid_embedding vector(768),
    article_count     INT DEFAULT 1,
    first_seen        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Articles: AI-processed news entries with semantic embeddings
CREATE TABLE IF NOT EXISTS articles (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    source_id        BIGINT REFERENCES rss_sources(id) ON DELETE SET NULL,
    event_id         UUID REFERENCES article_events(id) ON DELETE SET NULL,
    source_url       TEXT NOT NULL,
    title            TEXT NOT NULL,
    content          TEXT,
    summary          TEXT,
    why_it_matters   TEXT,
    topics           TEXT[] DEFAULT '{}',
    theme            TEXT,
    score            FLOAT DEFAULT 0.0,
    novelty_score    FLOAT DEFAULT 1.0,
    source_quality   FLOAT DEFAULT 0.5,
    embedding        vector(768),
    source           VARCHAR(100),
    is_delivered     BOOLEAN DEFAULT FALSE,
    v2_processed     BOOLEAN DEFAULT FALSE,
    published_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT articles_source_url_userid_key UNIQUE (source_url, user_id)
);

-- Source Health: Real-time telemetry for ingest quality
CREATE TABLE IF NOT EXISTS source_health (
    source_id         BIGINT NOT NULL REFERENCES rss_sources(id) ON DELETE CASCADE,
    user_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    articles_ingested INT DEFAULT 0,
    articles_delivered INT DEFAULT 0,
    articles_clicked  INT DEFAULT 0,
    duplicate_rate    FLOAT DEFAULT 0.0,
    quality_score     FLOAT DEFAULT 0.5,
    last_ingested_at  TIMESTAMPTZ,
    updated_at        TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (source_id, user_id)
);

-- User Feedback: Direct reinforcement signals
CREATE TABLE IF NOT EXISTS user_feedback (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    article_id  UUID REFERENCES articles(id) ON DELETE CASCADE,
    signal      TEXT NOT NULL CHECK (signal IN (
                  'clicked','saved','dismissed','more_like_this','less_like_this'
                )),
    comment     TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- App Config: Personalized AI pipeline settings
CREATE TABLE IF NOT EXISTS app_config (
    key        TEXT NOT NULL,
    user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (key, user_id)
);

-- Telemetry: Global pipeline performance metrics
CREATE TABLE IF NOT EXISTS telemetry (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    service     TEXT NOT NULL,
    metric_name TEXT,
    value       FLOAT8,
    metrics     JSONB NOT NULL,
    success     BOOLEAN DEFAULT TRUE,
    timestamp   TIMESTAMPTZ DEFAULT NOW()
);

-- AI Inference Logs: Audit trail for LLM executions
CREATE TABLE IF NOT EXISTS ai_inference_logs (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    article_id         UUID REFERENCES articles(id) ON DELETE SET NULL,
    service            TEXT NOT NULL,              -- e.g., 'summarizer', 'research_agent'
    model_name         TEXT NOT NULL,              -- e.g., 'qwen3-32b', 'llama-3.1-8b'
    prompt_tokens      INT NOT NULL,
    completion_tokens  INT NOT NULL,
    cost_usd           NUMERIC(10, 8),             -- Track financial spend
    latency_ms         INT NOT NULL,
    guardrail_status   TEXT CHECK (guardrail_status IN ('passed', 'flagged_safety', 'flagged_pii')),
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

-- Data Compliance Metadata: Privacy and classification tags
CREATE TABLE IF NOT EXISTS data_compliance_metadata (
    article_id         UUID PRIMARY KEY REFERENCES articles(id) ON DELETE CASCADE,
    classification     TEXT NOT NULL DEFAULT 'public' CHECK (classification IN ('public', 'confidential', 'restricted')),
    pii_scan_status    TEXT CHECK (pii_scan_status IN ('clean', 'scrubbed', 'failed')),
    pii_entities_found TEXT[],                     -- e.g. ['EMAIL', 'IP_ADDRESS']
    last_scanned_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Bias & Safety Reports: User-flagged issues for model auditing
CREATE TABLE IF NOT EXISTS bias_safety_reports (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    article_id         UUID REFERENCES articles(id) ON DELETE CASCADE,
    report_type        TEXT CHECK (report_type IN ('hallucination', 'bias', 'incorrect_summary', 'toxic')),
    user_comment       TEXT,
    resolved           BOOLEAN DEFAULT FALSE,
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ROBUSTNESS: Ensure new columns exist in existing tables
DO $$ 
BEGIN
    -- ── articles ──
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='articles' AND column_name='theme') THEN
        ALTER TABLE articles ADD COLUMN theme TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='articles' AND column_name='source_id') THEN
        ALTER TABLE articles ADD COLUMN source_id BIGINT REFERENCES rss_sources(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='articles' AND column_name='updated_at') THEN
        ALTER TABLE articles ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
    END IF;

    -- ── article_events ──
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='article_events' AND column_name='theme') THEN
        ALTER TABLE article_events ADD COLUMN theme TEXT;
    END IF;
    -- Unify last_updated -> updated_at
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='article_events' AND column_name='last_updated') AND
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='article_events' AND column_name='updated_at') THEN
        ALTER TABLE article_events RENAME COLUMN last_updated TO updated_at;
    ELSIF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='article_events' AND column_name='updated_at') THEN
        ALTER TABLE article_events ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
    END IF;

    -- ── source_health ──
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='source_health' AND column_name='last_ingested_at') THEN
        ALTER TABLE source_health ADD COLUMN last_ingested_at TIMESTAMPTZ;
    END IF;
    -- Unify last_updated -> updated_at
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='source_health' AND column_name='last_updated') AND
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='source_health' AND column_name='updated_at') THEN
        ALTER TABLE source_health RENAME COLUMN last_updated TO updated_at;
    ELSIF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='source_health' AND column_name='updated_at') THEN
        ALTER TABLE source_health ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
    END IF;

    -- ── user_feedback ──
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_feedback' AND column_name='updated_at') THEN
        ALTER TABLE user_feedback ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
    END IF;
    -- Migrate 'is_helpful' -> 'signal'
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_feedback' AND column_name='is_helpful') THEN
        ALTER TABLE user_feedback ADD COLUMN IF NOT EXISTS signal TEXT;
        UPDATE user_feedback SET signal = CASE WHEN is_helpful THEN 'clicked' ELSE 'dismissed' END WHERE signal IS NULL;
        ALTER TABLE user_feedback ALTER COLUMN signal SET NOT NULL;
        ALTER TABLE user_feedback DROP COLUMN is_helpful;
    END IF;

    -- Reload PostgREST schema cache
    NOTIFY pgrst, 'reload schema';
END $$;

-- 5. INDEXES (HNSW for high-performance vector search)
CREATE INDEX IF NOT EXISTS idx_articles_user_id      ON articles(user_id);
CREATE INDEX IF NOT EXISTS idx_articles_score        ON articles(score DESC);
CREATE INDEX IF NOT EXISTS idx_articles_theme        ON articles(theme);
CREATE INDEX IF NOT EXISTS idx_articles_created_at   ON articles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp   ON telemetry(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_rss_sources_user_id   ON rss_sources(user_id);

-- Drop old IVFFlat indexes if they exist
DROP INDEX IF EXISTS idx_articles_embedding;
DROP INDEX IF EXISTS idx_events_centroid;

-- HNSW: Significantly faster retrieval than IVFFlat for V2 scale
CREATE INDEX IF NOT EXISTS idx_articles_embedding_hnsw
  ON articles USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_events_centroid_hnsw
  ON article_events USING hnsw (centroid_embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- 6. TRIGGERS (IDEMPOTENT)
DROP TRIGGER IF EXISTS update_tenant_profiles_updated_at ON tenant_profiles;
CREATE TRIGGER update_tenant_profiles_updated_at BEFORE UPDATE ON tenant_profiles
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_rss_sources_updated_at ON rss_sources;
CREATE TRIGGER update_rss_sources_updated_at BEFORE UPDATE ON rss_sources
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_article_events_updated_at ON article_events;
CREATE TRIGGER update_article_events_updated_at BEFORE UPDATE ON article_events
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_app_config_updated_at ON app_config;
CREATE TRIGGER update_app_config_updated_at BEFORE UPDATE ON app_config
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_articles_updated_at ON articles;
CREATE TRIGGER update_articles_updated_at BEFORE UPDATE ON articles
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_feedback_updated_at ON user_feedback;
CREATE TRIGGER update_user_feedback_updated_at BEFORE UPDATE ON user_feedback
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 7. RPC FUNCTIONS

-- Semantic search per user
CREATE OR REPLACE FUNCTION match_articles(
  query_embedding  vector(768),
  match_threshold  float,
  match_count      int,
  p_user_id        uuid
) RETURNS TABLE (id uuid, title text, summary text, why_it_matters text, published_at timestamptz, similarity float)
LANGUAGE sql STABLE AS $$
  SELECT id, title, summary, why_it_matters, published_at, 1 - (embedding <=> query_embedding) AS similarity
  FROM articles WHERE user_id = p_user_id AND embedding IS NOT NULL AND 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC LIMIT match_count;
$$;

-- Near-duplicate check
CREATE OR REPLACE FUNCTION is_near_duplicate(query_embedding vector(768), dup_threshold float, p_user_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS (SELECT 1 FROM articles WHERE user_id = p_user_id AND embedding IS NOT NULL AND 1 - (embedding <=> query_embedding) >= dup_threshold);
$$;

-- Recency-weighted similarity (fuses content similarity with freshness)
CREATE OR REPLACE FUNCTION match_articles_recency(
  query_embedding  vector(768),
  match_count      int,
  p_user_id        uuid,
  decay_rate       float DEFAULT 0.15
)
RETURNS TABLE (id uuid, title text, summary text, recency_score float)
LANGUAGE sql STABLE AS $$
  SELECT
    id, title, summary,
    (1 - (embedding <=> query_embedding))
      * exp(-decay_rate * EXTRACT(EPOCH FROM (now() - COALESCE(published_at, created_at))) / 86400)
    AS recency_score
  FROM articles
  WHERE user_id = p_user_id
    AND embedding IS NOT NULL
  ORDER BY recency_score DESC
  LIMIT match_count;
$$;

-- Atomic increment for source ingestion tracking
CREATE OR REPLACE FUNCTION increment_source_ingestion(p_source_id bigint, p_user_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    INSERT INTO source_health (source_id, user_id, articles_ingested, updated_at)
    VALUES (p_source_id, p_user_id, 1, now())
    ON CONFLICT (source_id, user_id)
    DO UPDATE SET articles_ingested = source_health.articles_ingested + 1, updated_at = now();
END;
$$;

-- Atomic increment for article delivery tracking
CREATE OR REPLACE FUNCTION increment_source_delivery(p_source_id bigint, p_user_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    INSERT INTO source_health (source_id, user_id, articles_delivered, articles_clicked, quality_score, updated_at)
    VALUES (p_source_id, p_user_id, 1, 0, 0.5, now())
    ON CONFLICT (source_id, user_id)
    DO UPDATE SET
        articles_delivered = source_health.articles_delivered + 1,
        quality_score = GREATEST(0.1, LEAST(1.0,
            CASE
                WHEN (source_health.articles_delivered + 1) > 0
                THEN ROUND(source_health.articles_clicked::numeric / (source_health.articles_delivered + 1), 4)
                ELSE 0.5
            END
        )),
        updated_at = now();
END;
$$;

-- Atomic increment for article click tracking (called from the frontend)
CREATE OR REPLACE FUNCTION increment_source_click(p_source_id bigint, p_user_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    INSERT INTO source_health (source_id, user_id, articles_clicked, articles_delivered, quality_score, updated_at)
    VALUES (p_source_id, p_user_id, 1, 0, 0.5, now())
    ON CONFLICT (source_id, user_id)
    DO UPDATE SET
        articles_clicked = source_health.articles_clicked + 1,
        quality_score = GREATEST(0.1, LEAST(1.0,
            CASE
                WHEN source_health.articles_delivered > 0
                THEN ROUND((source_health.articles_clicked + 1)::numeric / source_health.articles_delivered, 4)
                ELSE 0.5
            END
        )),
        updated_at = now();
END;
$$;

-- Match thematic clusters
CREATE OR REPLACE FUNCTION match_events_by_centroid(query_embedding vector(768), threshold float, p_user_id uuid)
RETURNS TABLE (id uuid, article_count int, similarity float)
LANGUAGE sql STABLE AS $$
  SELECT id, article_count, 1 - (centroid_embedding <=> query_embedding) AS similarity
  FROM article_events WHERE user_id = p_user_id AND centroid_embedding IS NOT NULL AND 1 - (centroid_embedding <=> query_embedding) >= threshold
  ORDER BY similarity DESC LIMIT 5;
$$;

-- 8. ROW LEVEL SECURITY (RLS)
ALTER TABLE tenant_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE rss_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_inference_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_compliance_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE bias_safety_reports ENABLE ROW LEVEL SECURITY;

-- Role-aware tenant isolation policies

-- tenant_profiles
DROP POLICY IF EXISTS "Tenant isolation - Profiles" ON tenant_profiles;
CREATE POLICY "Profiles - own data or admin/auditor read" ON tenant_profiles FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "Profiles - own data write" ON tenant_profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Profiles - own data update" ON tenant_profiles FOR UPDATE USING (auth.uid() = user_id OR get_my_role() = 'admin');
CREATE POLICY "Profiles - admin delete only" ON tenant_profiles FOR DELETE USING (auth.uid() = user_id OR get_my_role() = 'admin');

-- app_config
DROP POLICY IF EXISTS "Tenant isolation - Config" ON app_config;
CREATE POLICY "Config - own data or admin/auditor read" ON app_config FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "Config - own data write" ON app_config FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Config - own data update" ON app_config FOR UPDATE USING (auth.uid() = user_id OR get_my_role() = 'admin');

-- rss_sources
DROP POLICY IF EXISTS "Tenant isolation - Sources" ON rss_sources;
CREATE POLICY "Sources - own data or admin/auditor read" ON rss_sources FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "Sources - quota-gated insert" ON rss_sources FOR INSERT WITH CHECK (auth.uid() = user_id AND can_add_rss_source(auth.uid()));
CREATE POLICY "Sources - own data update" ON rss_sources FOR UPDATE USING (auth.uid() = user_id OR get_my_role() = 'admin');
CREATE POLICY "Sources - own data delete" ON rss_sources FOR DELETE USING (auth.uid() = user_id OR get_my_role() = 'admin');

-- articles
DROP POLICY IF EXISTS "Tenant isolation - Articles" ON articles;
CREATE POLICY "Articles - own data or admin/auditor read" ON articles FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "Articles - own data write" ON articles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Articles - own data update" ON articles FOR UPDATE USING (auth.uid() = user_id OR get_my_role() = 'admin');
CREATE POLICY "Articles - own data delete" ON articles FOR DELETE USING (auth.uid() = user_id OR get_my_role() = 'admin');

-- article_events
DROP POLICY IF EXISTS "Tenant isolation - Events" ON article_events;
CREATE POLICY "Events - own data or admin/auditor read" ON article_events FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "Events - own data write" ON article_events FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Events - own data update" ON article_events FOR UPDATE USING (auth.uid() = user_id OR get_my_role() = 'admin');
CREATE POLICY "Events - own data delete" ON article_events FOR DELETE USING (auth.uid() = user_id OR get_my_role() = 'admin');

-- source_health
DROP POLICY IF EXISTS "Tenant isolation - Stats" ON source_health;
CREATE POLICY "SourceHealth - own data or admin/auditor read" ON source_health FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "SourceHealth - own data write" ON source_health FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "SourceHealth - own data update" ON source_health FOR UPDATE USING (auth.uid() = user_id OR get_my_role() = 'admin');

-- user_feedback
DROP POLICY IF EXISTS "Tenant isolation - Feedback" ON user_feedback;
CREATE POLICY "Feedback - own data or admin/auditor read" ON user_feedback FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "Feedback - own data write" ON user_feedback FOR INSERT WITH CHECK (auth.uid() = user_id AND get_my_role() IN ('admin', 'premium', 'user'));

-- telemetry
DROP POLICY IF EXISTS "Tenant isolation - Telemetry" ON telemetry;
CREATE POLICY "Telemetry - own data or admin/auditor read" ON telemetry FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "Telemetry - system write" ON telemetry FOR INSERT WITH CHECK (auth.uid() = user_id OR get_my_role() = 'admin');

-- ai_inference_logs
DROP POLICY IF EXISTS "Tenant isolation - AI Inference Logs" ON ai_inference_logs;
CREATE POLICY "AI Logs - own data or admin/auditor read" ON ai_inference_logs FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "AI Logs - system write" ON ai_inference_logs FOR INSERT WITH CHECK (auth.uid() = user_id OR get_my_role() = 'admin');

-- data_compliance_metadata
DROP POLICY IF EXISTS "Tenant isolation - Data Compliance" ON data_compliance_metadata;
CREATE POLICY "Compliance - own data or admin/auditor read" ON data_compliance_metadata FOR SELECT USING (
    EXISTS (SELECT 1 FROM articles WHERE id = article_id AND (user_id = auth.uid() OR get_my_role() IN ('admin', 'auditor')))
);
CREATE POLICY "Compliance - own data write" ON data_compliance_metadata FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM articles WHERE id = article_id AND user_id = auth.uid())
);
CREATE POLICY "Compliance - own data update" ON data_compliance_metadata FOR UPDATE USING (
    EXISTS (SELECT 1 FROM articles WHERE id = article_id AND (user_id = auth.uid() OR get_my_role() = 'admin'))
);

-- bias_safety_reports
DROP POLICY IF EXISTS "Tenant isolation - Bias Safety Reports" ON bias_safety_reports;
CREATE POLICY "Reports - own data or admin/auditor read" ON bias_safety_reports FOR SELECT USING (auth.uid() = user_id OR get_my_role() IN ('admin', 'auditor'));
CREATE POLICY "Reports - own data write" ON bias_safety_reports FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Reports - own data update" ON bias_safety_reports FOR UPDATE USING (auth.uid() = user_id OR get_my_role() = 'admin');

-- 9. INDEXES
CREATE INDEX IF NOT EXISTS idx_tenant_profiles_role ON tenant_profiles(role);
